---
- name: update soft
  hosts: all
  tasks:
    - apt: upgrade=safe update_cache=yes

    - apt_key: url=http://nginx.org/keys/nginx_signing.key state=present

    - apt_repository: repo='deb http://nginx.org/packages/ubuntu/ wily nginx' state=present

    - apt: name=nginx
      when: frontend_name.stdout.find('apache') != -1

- name: big install
  hosts: all
  tasks:
    - apt: name=git
    - apt: name=software-properties-common
    - apt: name=python-software-properties

